name: Regression and Unit Testing

on:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'feature_regressiontests'
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:

  run_regression:
    name: Run tests in container
    runs-on: ubuntu-latest
    steps:
      - name: Pre Cleanup
        uses: docker://ghcr.io/evertbunschoten/su2dataminer_test:latest
        with:
          entrypoint: /bin/rm 
          args: -rf src/

      - name: Run regression tests
        uses: docker://ghcr.io/evertbunschoten/su2dataminer_test:latest
        with:
          args: -b ${{ github.ref }} -s run_regression.py
      
      - name: Post Cleanup
        uses: docker://ghcr.io/evertbunschoten/su2dataminer_test:latest
        with:
          entrypoint: /bin/rm 
          args: -rf src/

  MLPcpp_tests:
    name: MLPCpp compatibility tests
    runs-on: ubuntu-latest 
    steps:
      - name: Pre Cleanup
        uses: docker://ghcr.io/evertbunschoten/su2dataminer_test:latest
        with:
          entrypoint: /bin/rm 
          args: -rf src/
          
      - name: MLPCpp integration tests
        uses: docker://ghcr.io/evertbunschoten/su2dataminer_test:latest
        with:
          args: -b ${{ github.ref }} -s MLPCpp_tests.py -m main

      - name: Post Cleanup
        uses: docker://ghcr.io/evertbunschoten/su2dataminer_test:latest
        with:
          entrypoint: /bin/rm 
          args: -rf src/